# Generated by Django 4.0.5 on 2022-06-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_order_taxprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='country',
        ),
    ]
