# Generated by Django 4.0.5 on 2022-06-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_county_shippingaddress_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
    ]
